version: "3.3"

services:
  url-shortener-mongodb:
    image: mongo
    container_name: url-shortener-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  memcached:
    image: memcached:latest
    container_name: url-shortener-memcached
    ports:
      - "11211:11211"
  url-shortener-api:
    build: .
    container_name: url-shortener-api
    ports:
      - "5000:5000"
    depends_on:
      - url-shortener-mongodb
      - memcached
    environment:
      - MONGO_URL=mongodb://url-shortener-mongodb:27017
      - MEMCACHED_URL=url-shortener-memcached:11211
      - BASE_SHORT_URL=http://localhost:5000/
    env_file:
      - ./src/.env
    volumes:
      - type: bind
        source: .
        target: /app/
        read_only: true

volumes:
  mongodb_data: